import React, { useState } from 'react'
import Spinner from './Spinner';
import useGif from '../hooks/useGif';


const API_KEY = process.env.REACT_APP_GIPHY_API_KEY;

const Tag = () => {
  const [tag, setTag] = useState('car');
  const {gif, loader, fetchData} = useGif(tag);

// All data which is comment out it is fetching with the help if "useGif" APi which is
// generated by me.

  // const [loader, setLoader] = useState("false");
  // const [gif, setGif] = useState(" ");

  // async function fetchData() {
  //   setLoader(true);
  //   const url = `https://api.giphy.com/v1/gifs/random?api_key=${API_KEY}&tag${tag}`;
  //   const { data } = await axios.get(url);
  //   const imageSource = data.data.images.downsized_large.url;
  //   setGif(imageSource);
  //   setLoader(false);
  // }

  // useEffect(() => {
  //   fetchData();
  // }, [])


  // function clickHandler() {
  //   fetchData();
  // }

  return (
  <div className='w-1/2 bg-blue-500 rounded-lg border border-black flex
    flex-col items-center gap-y-5 mt-[10px] mb-[10px]'>
      <h1 className='mt-[15px] text-2xl underline uppercase font-bold'>Random {tag} Gif</h1>

      {
        loader ? (<Spinner />) : (<img src={gif} width="350" />
        )
      }
    
      <input
        className='w-10/12 bg-white text-lg py-2 rounded-lg text-center'
        onChange={(event) => setTag(event.target.value)}
        value={tag}
      />

      <button onClick={() => fetchData(tag)}
        className='w-10/12 bg-slate-200 text-lg py-2 rounded-lg'>
        Generate
      </button>
    </div>
  )
}

export default Tag

